### ISSUE TITLE
what does it do?

### ISSUE THREAD

**Issue by allan-bonadio** [xiefucai/marked-admonition-extension#3]
Your description doesn't say what Admonition does.  An admonition in english is a gentle warning.  

an admonition to be careful

He offered words of advice and admonition.

And all surfers know the admonition about going out, into the water, with a buddy, or at least when there are others in the water.

So, it's not immediately obvious by reading your description of what it does.  You should start with an admonition or two in the description: 

   Warning: you must use Marked to use this extension!

   Note: this is a 'note' type admonition.  The warning above was a 'warning' type admonition.

People see these in docs all the time, they just don't know that the word 'admonition' is what they're called.  Putting in those two above would explain the concept by example.

**Comment by xiefucai** [comment]
@allan-bonadio Thank you for your advise, I have updated my description.
